### ISSUE TITLE
Meta data search with Document vectors

### ISSUE THREAD

**Issue by SriniNaga** [perone/euclidesdb#11]
I am not sure whether it is a new feature  or issue. But my requirement  is I have the documents like
[
{
   "domain":"ecommerce",
   "public":true,
   "date":"2018-09-12",
   "doc_vec": [-0.92,0.34,0.778...] ,# dimension 100
   "id":"hdh632387987"
},
{
   "domain":"media",
   "public":false,
   "date":"2018-09-12",
   "doc_vec": [-0.12,0.24,0.778...] ,# dimension 100
   "id":"hdh632383264687"
}
....
]
Required features:
1) First Filter by meta data(domain,publish,date)  and  then  similarity relevance for a given query doc
2)  Add/update/delete documents
3) Delete the documents after a given time period(1  month old)

**Comment by perone** [comment]
Hi @SriniNaga, thanks for your feedback. I thought about problems like that before designing the database, however, to do a search like that, it will require a metadata-aware database with document search, which is beyond the scope of EuclidesDB because I believe that you can implement that easily with any document database such as MongoDB and use EuclidesDB for the indexing/search only. Nowadays EuclidesDB saves metadata as a binary format, so it has no knowledge of what is within the metadata. That also poses many difficulties for approximate nearest neigh. search because you'll have to rebuild the index for some engines (such as annoy) for each filter before searching or filter the results after searching, and in both ways it's an expensive operation.
The document deletion/expiration is a very particular requirement, you can use MongoDB (I think they have a TTL feature) or even Redis to set an expiration as well.

**Comment by SriniNaga** [comment]
@perone Thank you !
