### ISSUE TITLE
Replace Annoy with Faiss as search engine ?

### ISSUE THREAD

**Issue by yupbank** [perone/euclidesdb#7]
So that we can use GPU to speed up the indexing

**Comment by perone** [comment]
That's a good idea, I'll evaluate that with more time after implementing the GPU support (need to evaluate how to distribute/link to CUDA libraries and libtorch-gpu). After this integration, I'll take a look at Faiss because it might have some integration issues to work together with libtorch-gpu. Thanks for posting this. 
Another comment, I'm trying to keep a design where I have "search engines", annoy is just one search engine, so we don't need to remove it, we just need to add Faiss as another search engine (together with linear search for example). This can be configurable in the EuclidesDB configuration files.

**Comment by perone** [comment]
CPU-only Faiss is now integrated with the search engine name `faiss`. Documentation is [here](https://euclidesdb.readthedocs.io/en/latest/configuration.html#faiss-configuration).
